name: Test

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - uses: actions/setup-go@v7
      with:
        go-version-file: go.mod

    - uses: actions/cache@v6
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Test
      run: |-
        go test \
          -count=1 \
          -race \
          -timeout=10m \
          -shuffle=on \
          ./...
